spring.application.name=ms-api-gateway
#recuerda que el uso de properties en java es muy importante si?
#server.port = 8080
server.port =${PORT:8080}
#muy importante
#clave para validar el JWT
#key.signature = XloYDteI0LNOvqDrsuRXInD/TNlkxh0Y8cWKSrmk9pwxT2UQxVqEKDt5IJHR3kWYOndi1wnXhgutCII6drunxw==
#postgresql://neondb_owner:npg_TPqIOAM5ns7b@ep-billowing-block-ac631ukw-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
key.signature = ${JWT_SECRET}
#ahora si definimos todas las rutas
#rutas internas de las apis que va a redireccionar
#ms.seguridad.url=http://localhost:8081
#ms.apis.externas.url= http://localhost:8082

ms.seguridad.url=${MS_SEGURIDAD_URL:http://localhost:8081}
ms.apis.externas.url= ${MS_APIS_EXTERNAS_URL:http://localhost:8082}

#definicion de rutas del gateway
#rutas para ms-seguridad:
spring.cloud.gateway.routes[0].id=ms-seguridad
spring.cloud.gateway.routes[0].uri=${ms.seguridad.url}
#en los prediccados nostorso definimos cuales son esas rutas que vamos a reconoces
spring.cloud.gateway.routes[0].predicates[0] = Path=/apis/codigo/api/authentication/**

#ahora si definimos las rutas para ms-apis-externas
spring.cloud.gateway.routes[1].id=apis-externas
spring.cloud.gateway.routes[1].uri=${ms.apis.externas.url}
#en los prediccados nostorso definimos cuales son esas rutas que vamos a reconoces
spring.cloud.gateway.routes[1].predicates[0] = Path=/apis/codigo/api/reniec/**

#RECUERDA QUE CON TODA ESTA CONFIGURACION -> NOSOTROS PODEMSO CONSUMIR CUALQUIER API EXTERNA Y TRABAJAR CON EL SI? RECUERDALO
